apiVersion: v1
kind: PersistentVolume
metadata:
  name: qwen3-weights-pv-v2
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-013265b82a90665e2
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-weights-src
  namespace: llasta
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 40Gi
  volumeName: qwen3-weights-pv-v2