apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen3
  namespace: llasta
spec:
  replicas: 1
  selector: { matchLabels: { app: vllm-qwen3 } }
  template:
    metadata:
      labels: { app: vllm-qwen3 }
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: vllm
          image: 142473567252.dkr.ecr.us-east-1.amazonaws.com/dockerhub/vllm/vllm-openai:v0.10.0
          # Conseil: pinner un tag (ex: v0.8.0) après le premier test au lieu de 'latest'
          args:
            - --model
            - /models/Qwen3-8B
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            - --max-model-len
            - "30160"
            - --dtype
            - auto
            - --served-model-name
            - Qwen3-8B
            - --gpu-memory-utilization
            - "0.95"
          ports:
            - { containerPort: 8000, name: http }
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: "14Gi"
            requests:
              cpu: "2"
              memory: "12Gi"
              nvidia.com/gpu: 1
          volumeMounts:
            - name: models
              mountPath: /models
          readinessProbe:
            httpGet:
              path: /v1/models
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: qwen3-weights-src
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-svc
  namespace: llasta
spec:
  type: ClusterIP
  selector: { app: vllm-qwen3 }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
