apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-weights-src
  namespace: llasta
spec:
  storageClassName: gp3
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 40Gi
