apiVersion: v1
kind: Pod
metadata:
  name: debug-volume
  namespace: llasta
spec:
  containers:
  - name: debug
    image: busybox
    command: ["sleep", "3600"]  # Reste actif 1 heure
    volumeMounts:
    - name: models
      mountPath: /models
  volumes:
  - name: models
    persistentVolumeClaim:
      claimName: qwen3-weights-src
  restartPolicy: Never
