apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  fsType: ext4
  # Tags automatiques pour tous les volumes créés avec cette StorageClass
  tagSpecification_1: "Key=Project,Value=llasta"
  tagSpecification_2: "Key=CreatedBy,Value=EBS-CSI-Driver"
  tagSpecification_3: "Key=ManagedBy,Value=Kubernetes"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-aws-vsc
driver: ebs.csi.aws.com
deletionPolicy: Retain
