apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: qwen3-weights-snap
  namespace: llasta
spec:
  source:
    persistentVolumeClaimName: qwen3-weights-src
  volumeSnapshotClassName: csi-aws-vsc
