apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-weights
  namespace: llasta
spec:
  storageClassName: gp3
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 40Gi
  dataSource:
    name: qwen3-weights-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
